quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5434/ecommerce
quarkus.hibernate-orm.database.generation=none

quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger
